/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Maheesha Madhuwantha
 */
public class splashScreen extends javax.swing.JFrame {

    /**
     * Creates new form splashScreen
     * 
     * 
     * 
     */
    
    
    public splashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        LoadingLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        BackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(204, 204, 204));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingLable.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        LoadingLable.setText("Loading....");
        BackGround.add(LoadingLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setText("welcome");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setText("COLOMBO INSTITUTE OF STUDIES");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        LoadingValue.setText("0 %");
        BackGround.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, -1, -1));
        BackGround.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 564, 980, 20));

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/undraw_Augmented_reality_re_f0qd.png"))); // NOI18N
        BackGroundImage.setText("jLabel1");
        BackGround.add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -40, 1020, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      splashScreen sp = new splashScreen();
      sp.setVisible(true); 
      try {
          for(int i=0;i<=100;i++){
              Thread.sleep(80);
              sp.LoadingValue.setText(i +"%");
              if (i==10) {
                  sp.LoadingLable.setText("Turing On Modules...");
              }
              if (i==20) {
                  sp.LoadingLable.setText("Loading Modules...");
              }
              if (i==50) {
                  sp.LoadingLable.setText("Connectiong To Database...");
              }
              if (i==70) {
                  sp.LoadingLable.setText("Connection Successfully...");
              }
              if (i==80) {
                  sp.LoadingLable.setText("Launching Application...");
              }
              sp.LoadingBar.setValue(i);
              }
          } catch (Exception e){
      }
      sp.setVisible(false);
      loginPage lp = new loginPage();
      lp.setVisible(true);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLable;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
